### PR TITLE
Wall time destroy effect

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
I don't know if you like it, but i had this laying around, and for some reason I can't put this to any wall of my mod. Maybe you like it.

### CODE REVIEW

**Comment by sk7725** [comment]
361 Calls? Mobile users and Hosts are gonna be soooooo mad

**Comment by sk7725** [comment]
You need to do something aboit that, 361 blocks in general will lag and is not a good practice.

**Comment by ThePythonGuy3** [comment]
It looks as good, and causes much less lag, I think it was too exagerated.

**Comment by sk7725** [comment]
According to Anuke, every Call is a separate Packet. :ohno:

**Comment by ThePythonGuy3** [comment]
Then nevermind.

**Pull request closed without merging**
