### PR TITLE
General Bleed of all Sprites

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
Thank me later

### CODE REVIEW

**Comment by sk7725** [comment]
1. have you made sure it does not fu:ohno:k up any of the shader blocks(walls, core:main, spatial storages, etc)
2. do you mind turning https://github.com/sk7725/Commandblocks/issues/61 into a proper zone PR complete with lore

**Comment by ThePythonGuy3** [comment]
1. Yup
2. Sure

**Comment by Eldoofus** [comment]
no @ThePythonGuy3 work on [enterprise secrets]

**Comment by ThePythonGuy3** [comment]
yes, but i can also add a lore to a map hhhhhhhhhhh

**Pull request merged**
