### PR TITLE
Shader for magicwalllarge

### PR DESCRIPTION
**Pull request by Sonnicon**
magicwalllarge now uses a shader to draw the colour change. Additionally, the change is now a wave instead of a solid colour loop.

image

### CODE REVIEW

**Comment by sk7725** [comment]
What. the. fuck. I love it

**Comment by sk7725** [comment]
A tad bit of problem:Android(not tested on IOS) does not support this feature. Can you find a way that works in Mobile?(Ill just add a if statement for now)

**Comment by sk7725** [comment]
WrappedException: Wrapped java.lang.IllegalArgumentException: Failed to compile shader: Fragment shader: 0:1: L0001: Storage qualifier not allowed in GLSL ES version 100 (magicwalllarge#3)

**Comment by Eldoofus** [comment]
Nothing works on iOS anyway. Don't ever bother with iOS.

**Pull request merged**
