### PR TITLE
스킬추가

### PR DESCRIPTION
**Pull request by younggam**
근접한 적 밀어내는 스킬

### CODE REVIEW

**Comment by sk7725** [comment]
아니 아저씨 스킬명잌ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by Eldoofus** [comment]
Dammit sk go make JK Flip Flop

**Comment by ghost** [comment]
ani

**Comment by sk7725** [comment]
I am a free spirit noone can stop me

**Comment by ghost** [comment]
School will stop you.

**Comment by Eldoofus** [comment]
I will stop you with my spam pinging autohotkey script

**Pull request merged**
