### PR TITLE
h

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
h

### CODE REVIEW

**Comment by ghost** [comment]
no

**Comment by ThePythonGuy3** [comment]
# yes

**Comment by ghost** [comment]
# no

**Comment by ThePythonGuy3** [comment]
****yes****

**Comment by sk7725** [comment]
Make a way to make it better executed, like give the player the bleach status effect.

**Comment by ghost** [comment]
That means after the button blows up, it bleaches the game permanently.

**Comment by ThePythonGuy3** [comment]
That's the point
# h

**Comment by sk7725** [comment]
then actually make it permanent

**Comment by ThePythonGuy3** [comment]
ok

**Comment by ThePythonGuy3** [comment]
Done(?)

**Comment by sk7725** [comment]
1. bleach should be globla
2. lag
3. == not =
4. ...just no why would you do that

**Comment by ThePythonGuy3** [comment]
1. yes
2. no
3. yes
4. Big RED Button

**Comment by sk7725** [comment]
I have another idea. Only bleach the kicked user's screen so the title screen is white. Dont do that for the server owner though.

**Comment by sk7725** [comment]
This PR is now irrelevant

**Pull request closed without merging**
