### PR TITLE
Shadum Bomb Modded Skill

### PR DESCRIPTION
**Pull request by snack-ie**
I'm new to this, so i just copied and pasted coal bomb 😂

### CODE REVIEW

**Comment by snack-ie** [comment]
I have some basic js knowledge so i don't make mistakes like forgetting the commas at the end of lists ;p

**Comment by snack-ie** [comment]
i forgot a comma

**Comment by snack-ie** [comment]
I can't ,-,

**Comment by sk7725** [comment]
what do you want your shadum bomb to do? I can make one

**Comment by snack-ie** [comment]
just be a simple bomb that explodes

**Pull request merged**
