### PR TITLE
software

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ThePythonGuy3** [comment]
lmao

**Comment by ThePythonGuy3** [comment]
did you realize that a software cant be a material, right?

**Comment by ThePythonGuy3** [comment]
sk, use this: A piece of software used to communicate directly with the host

**Comment by ghost** [comment]
> did you realize that a software cant be a material, right?

*Almost every item in this mod is program related, so it can be a material*

# h

**Comment by ThePythonGuy3** [comment]
# no

**Pull request merged**
