### PR TITLE
surge slime

### PR DESCRIPTION
**Pull request by Eldoofus**

### CODE REVIEW

**Comment by sk7725** [comment]
what's the point? if you want to make it produce power, make it hasPower and producesPower(did I spell that right idk see zeta walls)

**Comment by Eldoofus** [comment]
right
its not supposed to produce power, just conduct it

**Comment by sk7725** [comment]
outputsPower must be true to conduct, maybe? @Gdeft

**Comment by Eldoofus** [comment]
just merge it to test it

**Comment by Eldoofus** [comment]
wait! i know! just extend PowerDistributor instead of Block, will that work

**Comment by sk7725** [comment]
Implemented.

**Pull request closed without merging**
