### PR TITLE
surge skill time

### PR DESCRIPTION
**Pull request by ThatOneBepis**

### CODE REVIEW

**Comment by sk7725** [comment]
One problem: surge skilles are already planned, just not pushed yet. Can you come up with skills using your modded Items(Infinitodustry has a heck lot of em)

**Comment by ghost** [comment]
~~I still don't get it~~.

**Comment by ThatOneBepis** [comment]
~~Oh but i really cannot think of any themes for any resources, except for "blast resistance"~~

**Comment by sk7725** [comment]
You have scalars and vectors and all that goodness stuff!

**Comment by ghost** [comment]
sue time

**Comment by ThatOneBepis** [comment]
Eh, i guess i could do this
Vector - Mid-tier movement skills
Tensor - High-tier movement skills
Blast fabric - Blast-resistant/Lightning-resistant defensive and an advanced "coalbomb" skill
Infiar - Passive skills
Toughitinum - Energy offensive/defensive skills
Matrix - Mid-tier Supportive skills

**Comment by sk7725** [comment]
I have a cool (and probably fuxed up) idea: Make our Scalar, Vectors and Tensors intergratable

**Comment by sk7725** [comment]
When both our mods are enabled, all the factories should accept both Vectors from both mods

**Comment by Eldoofus** [comment]
why do that when u can make scalars and vectors from both mods just be the same item

**Comment by sk7725** [comment]
one cannot just do that easily

**Comment by sk7725** [comment]
All 3 skills have been implemented and/or sceduled. This PR is now irrelevant.

**Pull request closed without merging**
