### PR TITLE
ONLY FOR MOBILE

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
# h

### CODE REVIEW

**Comment by ghost** [comment]
Damage.damage(tile.drawx(), tile.drawy(), 1240, 400 * 8)

**Comment by ThePythonGuy3** [comment]
no, just kill it directly

**Comment by ghost** [comment]
kill everything

**Comment by ThePythonGuy3** [comment]
no

**Comment by ThePythonGuy3** [comment]
Big Red Button?

**Comment by ghost** [comment]
It plays music this time

**Comment by ThePythonGuy3** [comment]
yes

**Comment by sk7725** [comment]
Irrelevent now, closing.

**Pull request closed without merging**
